name: build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry env use 3.10
      - run: poetry install
      - run: poetry run autoflake --check -i -r --remove-all-unused-imports .
      - run: poetry run isort --check --atomic .
      - run: poetry run black --check .
      - run: poetry run mypy .
      - run: poetry run pytest
